spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/myshop?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    suffix: .html
  application:
    name: merchant
server:
  port: 8083